package com.bladderdiary.app.ui.theme

import androidx.compose.ui.graphics.Color

// Light Theme
val PrimaryLight = Color(0xFF2F5D67)
val OnPrimaryLight = Color(0xFFFFFFFF)
val PrimaryContainerLight = Color(0xFFD8E7EA)
val OnPrimaryContainerLight = Color(0xFF14363E)
val SecondaryLight = Color(0xFF5D7178)
val OnSecondaryLight = Color(0xFFFFFFFF)
val SecondaryContainerLight = Color(0xFFE2EBEE)
val OnSecondaryContainerLight = Color(0xFF20343B)
val TertiaryLight = Color(0xFF5E7F72)
val OnTertiaryLight = Color(0xFFFFFFFF)
val TertiaryContainerLight = Color(0xFFDCEADE)
val OnTertiaryContainerLight = Color(0xFF1D352D)
val BackgroundLight = Color(0xFFF4F7F8)
val OnBackgroundLight = Color(0xFF172126)
val SurfaceLight = Color(0xFFFFFFFF)
val OnSurfaceLight = Color(0xFF172126)
val SurfaceVariantLight = Color(0xFFECF1F2)
val OnSurfaceVariantLight = Color(0xFF4B5B61)
val OutlineLight = Color(0xFFC4CDD1)
val ErrorLight = Color(0xFFB3261E)
val OnErrorLight = Color(0xFFFFFFFF)

// Dark Theme
val PrimaryDark = Color(0xFF9FC2CB)
val OnPrimaryDark = Color(0xFF18363D)
val PrimaryContainerDark = Color(0xFF27464E)
val OnPrimaryContainerDark = Color(0xFFD8E7EA)
val SecondaryDark = Color(0xFFB5C4C9)
val OnSecondaryDark = Color(0xFF22363C)
val SecondaryContainerDark = Color(0xFF33464C)
val OnSecondaryContainerDark = Color(0xFFDCE5E7)
val TertiaryDark = Color(0xFFA3C2B2)
val OnTertiaryDark = Color(0xFF21372E)
val TertiaryContainerDark = Color(0xFF30483D)
val OnTertiaryContainerDark = Color(0xFFD6E7DC)
val BackgroundDark = Color(0xFF11181B)
val OnBackgroundDark = Color(0xFFE2E9EB)
val SurfaceDark = Color(0xFF182125)
val OnSurfaceDark = Color(0xFFE2E9EB)
val SurfaceVariantDark = Color(0xFF243036)
val OnSurfaceVariantDark = Color(0xFFB7C3C8)
val OutlineDark = Color(0xFF415058)
val ErrorDark = Color(0xFFFFB4AB)
val OnErrorDark = Color(0xFF690005)

val SuccessContainerLight = Color(0xFFDDEDDD)
val OnSuccessContainerLight = Color(0xFF1F4B31)
val WarningContainerLight = Color(0xFFF7EACB)
val OnWarningContainerLight = Color(0xFF5D4300)
val SecurityContainerLight = Color(0xFFE3EAF4)
val OnSecurityContainerLight = Color(0xFF243B63)

val SuccessContainerDark = Color(0xFF243A2C)
val OnSuccessContainerDark = Color(0xFFB8D8C1)
val WarningContainerDark = Color(0xFF4A3A12)
val OnWarningContainerDark = Color(0xFFF7E7BF)
val SecurityContainerDark = Color(0xFF233247)
val OnSecurityContainerDark = Color(0xFFC6D6F2)
