package com.bladderdiary.app.ui.theme

import androidx.compose.ui.graphics.Color

// 라이트 테마
val PrimaryLight = Color(0xFF006767)
val OnPrimaryLight = Color(0xFFFFFFFF)
val PrimaryContainerLight = Color(0xFF1E8181)
val OnPrimaryContainerLight = Color(0xFFF3FFFE)
val SecondaryLight = Color(0xFF426464)
val OnSecondaryLight = Color(0xFFFFFFFF)
val SecondaryContainerLight = Color(0xFFC2E7E6)
val OnSecondaryContainerLight = Color(0xFF294C4C)
val TertiaryLight = Color(0xFF2A5D5D)
val OnTertiaryLight = Color(0xFFFFFFFF)
val TertiaryContainerLight = Color(0xFFDCEFF0)
val OnTertiaryContainerLight = Color(0xFF123536)
val BackgroundLight = Color(0xFFF5FAFA)
val OnBackgroundLight = Color(0xFF171D1D)
val SurfaceLight = Color(0xFFFFFFFF)
val OnSurfaceLight = Color(0xFF171D1D)
val SurfaceVariantLight = Color(0xFFDEE3E3)
val OnSurfaceVariantLight = Color(0xFF3E4948)
val OutlineLight = Color(0xFFBDC9C8)
val ErrorLight = Color(0xFFB3261E)
val OnErrorLight = Color(0xFFFFFFFF)

// 다크 테마
val PrimaryDark = Color(0xFF80D6D5)
val OnPrimaryDark = Color(0xFF003737)
val PrimaryContainerDark = Color(0xFF005050)
val OnPrimaryContainerDark = Color(0xFFD6FFFE)
val SecondaryDark = Color(0xFFABCFCF)
val OnSecondaryDark = Color(0xFF103738)
val SecondaryContainerDark = Color(0xFF294C4C)
val OnSecondaryContainerDark = Color(0xFFC6EBEA)
val TertiaryDark = Color(0xFFA7D0D0)
val OnTertiaryDark = Color(0xFF153738)
val TertiaryContainerDark = Color(0xFF224B4B)
val OnTertiaryContainerDark = Color(0xFFD0F3F2)
val BackgroundDark = Color(0xFF0D1414)
val OnBackgroundDark = Color(0xFFE8F0F0)
val SurfaceDark = Color(0xFF141D1D)
val OnSurfaceDark = Color(0xFFE8F0F0)
val SurfaceVariantDark = Color(0xFF253030)
val OnSurfaceVariantDark = Color(0xFFBDC9C8)
val OutlineDark = Color(0xFF546262)
val ErrorDark = Color(0xFFFFB4AB)
val OnErrorDark = Color(0xFF690005)

val SuccessContainerLight = Color(0xFFE2F4EE)
val OnSuccessContainerLight = Color(0xFF0F5246)
val WarningContainerLight = Color(0xFFFFE9D8)
val OnWarningContainerLight = Color(0xFF7A4100)
val SecurityContainerLight = Color(0xFFE7F0F0)
val OnSecurityContainerLight = Color(0xFF1D5353)

val SuccessContainerDark = Color(0xFF163A33)
val OnSuccessContainerDark = Color(0xFFBEEADE)
val WarningContainerDark = Color(0xFF4D2E12)
val OnWarningContainerDark = Color(0xFFFFDDBF)
val SecurityContainerDark = Color(0xFF183535)
val OnSecurityContainerDark = Color(0xFFBFE7E7)
